=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FattureInCloud_Ruby_Sdk::CashbookApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CashbookApi' do
  before do
    # run before each test
    @api_instance = FattureInCloud_Ruby_Sdk::CashbookApi.new

    @create_cashbook_entry_response_obj = { "data": { "date": "2021-08-24", "amount_out": 122, "payment_account_out": { "id": 333 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "out" } }
    allow(@api_instance).to receive(:create_cashbook_entry) { @create_cashbook_entry_response_obj }

    @get_cashbook_entry_response_obj = { "data": { "date": "2021-08-24", "amount_out": 122, "payment_account_out": { "id": 333 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "out" } }
    allow(@api_instance).to receive(:get_cashbook_entry) { @get_cashbook_entry_response_obj }

    @modify_cashbook_entry_response_obj = { "data": { "date": "2021-08-24", "amount_out": 122, "payment_account_out": { "id": 333 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "out" } }
    allow(@api_instance).to receive(:modify_cashbook_entry) { @modify_cashbook_entry_response_obj }

    @list_cashbook_entries_response_obj = { "data": [{ "date": "2021-08-24", "amount_in": 122, "payment_account_in": { "id": 333 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "in" }, { "date": "2021-08-29", "amount_out": 211, "payment_account_out": { "id": 444 }, "description": "Fattura n. 202\/2021", "entity_name": "Red S.r.l.", "kind": "issued_document", "document": { "id": 12345 }, "type": "out" }] }
    allow(@api_instance).to receive(:list_cashbook_entries) { @list_cashbook_entries_response_obj }

  end

  after do
    # run after each test
  end

  describe 'test an instance of CashbookApi' do
    it 'should create an instance of CashbookApi' do
      expect(@api_instance).to be_instance_of(FattureInCloud_Ruby_Sdk::CashbookApi)
    end
  end

  # unit tests for create_cashbook_entry
  # Create Cashbook Entry
  # Creates a new cashbook entry.
  # @param company_id The ID of the company.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateCashbookEntryRequest] :create_cashbook_entry_request Cashbook entry. 
  # @return [CreateCashbookEntryResponse]
  describe 'create_cashbook_entry test' do
    it 'should work' do
      opts = { "data": { "date": "2021-08-24", "amount_in": 122, "payment_account_in": { "id": 21 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "in" } }
      response = @api_instance.create_cashbook_entry(2, opts)
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @create_cashbook_entry_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

  # unit tests for delete_cashbook_entry
  # Delete Cashbook Entry
  # Deletes the specified cashbook entry.
  # @param company_id The ID of the company.
  # @param document_id The ID of the document.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_cashbook_entry test' do
    it 'should work' do
      expect(true).to eq(true)
    end
  end

  # unit tests for get_cashbook_entry
  # Get Cashbook Entry
  # Gets the specified cashbook entry.
  # @param company_id The ID of the company.
  # @param document_id The ID of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields List of comma-separated fields.
  # @option opts [String] :fieldset Name of the fieldset.
  # @return [GetCashbookEntryResponse]
  describe 'get_cashbook_entry test' do
    it 'should work' do
      response = @api_instance.get_cashbook_entry(2, 22)
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @get_cashbook_entry_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

  # unit tests for list_cashbook_entries
  # List Cashbook Entries
  # Lists the cashbook entries.
  # @param company_id The ID of the company.
  # @param date_from Start date.
  # @param date_to End date.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Filter cashbook by year.
  # @option opts [String] :type Filter cashbook by type.
  # @option opts [Integer] :payment_account_id Filter by payment account.
  # @return [ListCashbookEntriesResponse]
  describe 'list_cashbook_entries test' do
    it 'should work' do
      response = @api_instance.list_cashbook_entries(2, "2020-12-12", "2021-12-12")
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @list_cashbook_entries_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

  # unit tests for modify_cashbook_entry
  # Modify Cashbook Entry
  # Modifies the specified cashbook entry.
  # @param company_id The ID of the company.
  # @param document_id The ID of the document.
  # @param [Hash] opts the optional parameters
  # @option opts [ModifyCashbookEntryRequest] :modify_cashbook_entry_request Cashbook Entry
  # @return [ModifyCashbookEntryResponse]
  describe 'modify_cashbook_entry test' do
    it 'should work' do
      opts = { "data": { "date": "2021-08-24", "amount_in": 122, "payment_account_in": { "id": 21 }, "description": "Fattura n. 201\/2021", "entity_name": "Rossi S.r.l.", "kind": "issued_document", "document": { "id": 54321 }, "type": "in" } }
      response = @api_instance.modify_cashbook_entry(2, opts)
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @modify_cashbook_entry_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

end
