=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.1.5
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FattureInCloud_Ruby_Sdk::PriceListsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PriceListsApi' do
  before do
    # run before each test
    @api_instance = FattureInCloud_Ruby_Sdk::PriceListsApi.new

    @get_price_lists_response_obj = { data: [{ id: '10', name: 'listino', prices_type: 'net', is_default: true, valid_from: '2025-01-01', valid_to: '2025-12-01', type: 'sell' }, { id: '11', name: 'listino-test', prices_type: 'gross', is_default: true, valid_from: '2025-01-01', valid_to: '2025-01-01', type: 'purchase' }] }
    allow(@api_instance).to receive(:get_price_lists) { @get_price_lists_response_obj }

    @get_price_list_items_response_obj = { data: { '1': { price: 3.5 }, '2': { price: 5 } } }
    allow(@api_instance).to receive(:get_price_list_items) { @get_price_list_items_response_obj }

  end

  after do
    # run after each test
  end

  describe 'test an instance of PriceListsApi' do
    it 'should create an instance of PriceListsApi' do
      expect(@api_instance).to be_instance_of(FattureInCloud_Ruby_Sdk::PriceListsApi)
    end
  end

  # unit tests for get_price_list_items
  # Get PriceList Items List
  # Retrieves all the Items of a PriceList
  # @param company_id The ID of the company.
  # @param price_list_id
  # @param [Hash] opts the optional parameters
  # @return [GetPriceListItemsResponse]
  describe 'get_price_list_items test' do
    it 'should work' do
      response = @api_instance.get_price_list_items(2, '10')
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @get_price_list_items_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

  # unit tests for get_price_lists
  # Get PriceLists
  # Retrieves all price lists of the company
  # @param company_id The ID of the company.
  # @param [Hash] opts the optional parameters
  # @return [ListPriceListsResponse]
  describe 'get_price_lists test' do
    it 'should work' do
      response = @api_instance.get_price_lists(2)
      response_obj = JSON.parse(response.to_json, object_class: OpenStruct)
      expected_json = @get_price_lists_response_obj.to_json
      actual_json = response.to_json

      expect(actual_json).to eq(expected_json)
    end
  end

end
