=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::CreateReceivedDocumentRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::CreateReceivedDocumentRequest do
  instance = FattureInCloud_Ruby_Sdk::CreateReceivedDocumentRequest.new
  instance.pending_id = 5;
    instance.data = {
        id: 12345,
        type: "expense",
        description: "Soggiorno di lavoro",
        amortization: 1,
        rc_center: "",
        invoice_number: "",
        is_marked: false,
        is_detailed: false,
        e_invoice: false,
        entity: {
          id: 111,
          name: "Hotel Rubino Palace"
        },
        date: "2021-08-15",
        next_due_date: "2021-08-15",
        currency: {
          id: "EUR",
          exchange_rate: "1.00000",
          symbol: "€"
        },
        amount_net: 592,
        amount_vat: 0,
        amount_gross: 592,
        amount_withholding_tax: 0,
        amount_other_withholding_tax: 0,
        tax_deductibility: 50,
        vat_deductibility: 100,
        payments_list: [
          {
            amount: 592,
            due_date: "2021-08-15",
            paid_date: "2021-08-15",
            id: 777,
            payment_terms: {
              days: 0,
              type: "standard"
            },
            status: "paid",
            payment_account: {
              id: 222,
              name: "Contanti",
              virtual: false
            }
          }
        ],
        attachment_url: "spesa_ger5i783t45hu6ti.pdf"
    }
    
  describe 'test an instance of CreateReceivedDocumentRequest' do
    it 'should create an instance of CreateReceivedDocumentRequest' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::CreateReceivedDocumentRequest)
    end
  end
  describe 'test attribute "pending_id"' do
    it 'should work' do
      expect(instance.pending_id).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
