=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.27
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::GetWebhooksSubscriptionResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::GetWebhooksSubscriptionResponse do
  instance = FattureInCloud_Ruby_Sdk::GetWebhooksSubscriptionResponse.new
  instance.data = {
    id: 'SUB123',
    sink: 'https://endpoint.test',
    verified: true,
    types: ['it.fattureincloud.cashbook.create']
  }

  describe 'test an instance of GetWebhooksSubscriptionResponse' do
    it 'should create an instance of GetWebhooksSubscriptionResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::GetWebhooksSubscriptionResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
