=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::GetReceiptPreCreateInfoResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::GetReceiptPreCreateInfoResponse do
  instance = FattureInCloud_Ruby_Sdk::GetReceiptPreCreateInfoResponse.new
  instance.data = {
    numerations: {
        "2016": {
          sales_receipt: {
            REC003: 12,
            REC002: 5,
            REC001: 2
          },
          till_receipt: {
            REC002: 6,
            REC001: 2
          }
        },
        "2017": {
          sales_receipt: {
            REC003: 14,
            REC002: 7,
            REC001: 1
          },
          till_receipt: {
            REC003: 1,
            REC001: 3
          }
        },
        "2018": {
          sales_receipt: {
            REC001: 3
          }
        },
        "2019": {
          sales_receipt: {
            REC002: 105,
            REC001: 22
          },
          till_receipt: {
            REC003: 21,
            REC002: 24,
            REC001: 25
          }
        },
        "2020": {
          sales_receipt: {
            REC001: 3
          }
        },
        "2021": {
          sales_receipt: {
            REC005: 3,
            REC004: 2,
            REC003: 2,
            REC001: 7
          }
        }
      },
      numerations_list: [
        "REC001",
        "REC002",
        "REC003",
        "REC005",
        "REC006"
      ],
      rc_centers_list: [
        "Sede generale",
        "Negozio Bergamo",
        "Negozio Milano"
      ],
      payment_accounts_list: [
        {
          id: 111,
          name: "Indesa - carta conto"
        }
    ]
  }
  describe 'test an instance of GetReceiptPreCreateInfoResponse' do
    it 'should create an instance of GetReceiptPreCreateInfoResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::GetReceiptPreCreateInfoResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
