=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::IssuedDocument
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::IssuedDocument do
  instance = FattureInCloud_Ruby_Sdk::IssuedDocument.new
  instance.id = 12345
  instance.type = "receipt"
  instance.year = 2021
  instance.numeration = "rec123"
  instance.subject = ""
  instance.visible_subject = ""
  instance.rc_center = ""
  instance.ei_cassa_type = ""
  instance.ei_withholding_tax_causal = "a"
  instance.ei_other_withholding_tax_type = "a"
  instance.ei_other_withholding_tax_causal = "c"
  instance.stamp_duty = 0
  instance.use_gross_prices = false
  instance.e_invoice = false
  instance.delivery_note = false
  instance.accompanying_invoice = false
  instance.amount_net = 68.18
  instance.amount_vat = 6.82
  instance.amount_gross = 75.0
  instance.amount_due_discount = 1.0
  instance.amount_rivalsa = 0.0
  instance.amount_cassa = 0.0
  instance.amount_withholding_tax = 0.0
  instance.amount_other_withholding_tax = 0.0
  instance.h_margins = 15
  instance.v_margins = 16
  instance.show_payment_method = false
  instance.show_payments = true
  instance.show_totals = "all"
  instance.show_notification_button = false
  instance.is_marked = false
  instance.date = Date.new(2021, 12, 21)
  instance.number = 1
  instance.notes = ""
  instance.rivalsa = 0.0
  instance.cassa = 0.0
  instance.withholding_tax = 0.0
  instance.withholding_tax_taxable = 100.0
  instance.other_withholding_tax = 0.0
  instance.use_split_payment = false
  instance.attachment_url = "kdijrnf893hnwkfk45f50f.pdf"
  instance.seen_date = Date.new(2021, 12, 21)
  instance.next_due_date = Date.new(2021, 12, 21)
  instance.url = "y12h45rn9yf2mse0p43t7ec90vr.pdf"
  instance.show_tspay_button = false
  instance.dn_number = 3
  instance.dn_date = Date.new(2021, 12, 21)
  instance.dn_ai_packages_number = 4
  instance.dn_ai_weight = 3
  instance.dn_ai_causal = "causal"
  instance.dn_ai_destination = "dest"
  instance.dn_ai_transporter = "trasp"
  instance.dn_ai_notes = "notes"
  instance.amount_rivalsa_taxable = 3.0
  instance.amount_global_cassa_taxable = 3.0
  instance.amount_cassa_taxable = 3.0
  instance.amount_cassa2 = 3.0
  instance.amount_cassa2_taxable = 3.0
  instance.amount_withholding_tax_taxable = 3.0
  instance.amount_enasarco_taxable = 3.0
  instance.amount_other_withholding_tax_taxable = 3.0
  instance.ei_cassa2_type = ""
  instance.attachment_token = "asdaosdjaoisndoa"
  instance.entity = {
   id: 54321,
   name: "Mary Red S.r.L.",
   vat_number: "IT05432181211",
   tax_code: "IT05432181211",
   address_street: "Corso impero, 66",
   address_postal_code: "20900",
   address_city: "Milano",
   address_province: "MI",
   address_extra: "",
   country: "Italia",
   certified_email: "mary@pec.red.com",
   ei_code: "ABCXCR1"
    },
  instance.currency = {
   id: "EUR",
   exchange_rate: "1.00000",
   symbol: "€"
    },
  instance.language = {
   code: "it",
   name: "Italiano"
    },
  instance.payment_method = {
   id: 4,
   name: "Credit card"
    },
  instance.items_list = [
   {
     product_id: 5432,
     code: "SG3",
     name: "Soggiorno",
     measure: "",
     net_price: 68.18182,
     category: "",
     id: 277876033,
     gross_price: 75,
     apply_withholding_taxes: true,
     discount: 0,
     discount_highlight: false,
     in_dn: false,
     qty: 1,
     vat: {
       id: 3,
       value: 10,
       description: ""
     },
     stock: false,
     description: "",
     not_taxable: false
   }
 ],
  instance.payments_list = [
   {
     amount: 75,
     due_date: Date.new(2021, 12, 21),
     paid_date: nil,
     id: 69078013,
     payment_terms: {
       days: 0,
       type: "standard"
     },
     status: "not_paid",
     payment_account: nil
   }
    ],
  instance.template = {
   id: 2821,
   name: "Light Smoke"
    },
  instance.extra_data = {
   ts_status: 1
    },
  instance.acc_inv_template = {
   id: 4
    },
  instance.delivery_note_template = {
   id: 54321
    },
  instance.ei_raw = {
   prop: true
    },
  instance.ei_data = {
   bank_name: "Sao Paulo"
    }

  describe 'test an instance of IssuedDocument' do
    it 'should create an instance of IssuedDocument' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::IssuedDocument)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance.id).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "entity"' do
    it 'should work' do
      expect(instance.entity).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      expect(instance.type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "number"' do
    it 'should work' do
      expect(instance.number).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "numeration"' do
    it 'should work' do
      expect(instance.numeration).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      expect(instance.date).to be_a_kind_of(Date)
    end
  end

  describe 'test attribute "currency"' do
    it 'should work' do
      expect(instance.currency).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "language"' do
    it 'should work' do
      expect(instance.language).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "subject"' do
    it 'should work' do
      expect(instance.subject).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "visible_subject"' do
    it 'should work' do
      expect(instance.visible_subject).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "rc_center"' do
    it 'should work' do
      expect(instance.rc_center).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "notes"' do
    it 'should work' do
      expect(instance.notes).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "rivalsa"' do
    it 'should work' do
      expect(instance.rivalsa).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "cassa"' do
    it 'should work' do
      expect(instance.cassa).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "withholding_tax"' do
    it 'should work' do
      expect(instance.withholding_tax).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "withholding_tax_taxable"' do
    it 'should work' do
      expect(instance.withholding_tax_taxable).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "other_withholding_tax"' do
    it 'should work' do
      expect(instance.other_withholding_tax).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "stamp_duty"' do
    it 'should work' do
      expect(instance.stamp_duty).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "payment_method"' do
    it 'should work' do
      expect(instance.payment_method).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "use_split_payment"' do
    it 'should work' do
      expect(instance.use_split_payment).to be(true).or be(false)
    end
  end

  describe 'test attribute "use_gross_prices"' do
    it 'should work' do
      expect(instance.use_gross_prices).to be(true).or be(false)
    end
  end

  describe 'test attribute "e_invoice"' do
    it 'should work' do
      expect(instance.e_invoice).to be(true).or be(false)
    end
  end

  describe 'test attribute "ei_data"' do
    it 'should work' do
      expect(instance.ei_data).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "items_list"' do
    it 'should work' do
      expect(instance.items_list).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "payments_list"' do
    it 'should work' do
      expect(instance.payments_list).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "template"' do
    it 'should work' do
      expect(instance.template).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "delivery_note_template"' do
    it 'should work' do
      expect(instance.delivery_note_template).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "acc_inv_template"' do
    it 'should work' do
      expect(instance.acc_inv_template).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "h_margins"' do
    it 'should work' do
      expect(instance.h_margins).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "show_payments"' do
    it 'should work' do
      expect(instance.show_payments).to be(true).or be(false)
    end
  end

  describe 'test attribute "show_payment_method"' do
    it 'should work' do
      expect(instance.show_payment_method).to be(true).or be(false)
    end
  end

  describe 'test attribute "show_totals"' do
    it 'should work' do
      expect(instance.show_totals).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "v_margins"' do
    it 'should work' do
      expect(instance.v_margins).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "show_notification_button"' do
    it 'should work' do
      expect(instance.show_notification_button).to be(true).or be(false)
    end
  end

  describe 'test attribute "delivery_note"' do
    it 'should work' do
      expect(instance.delivery_note).to be(true).or be(false)
    end
  end

  describe 'test attribute "accompanying_invoice"' do
    it 'should work' do
      expect(instance.accompanying_invoice).to be(true).or be(false)
    end
  end

  describe 'test attribute "dn_number"' do
    it 'should work' do
      expect(instance.dn_number).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "dn_date"' do
    it 'should work' do
      expect(instance.dn_date).to be_a_kind_of(Date)
    end
  end

  describe 'test attribute "dn_ai_packages_number"' do
    it 'should work' do
      expect(instance.dn_ai_packages_number).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "dn_ai_weight"' do
    it 'should work' do
      expect(instance.dn_ai_weight).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "dn_ai_causal"' do
    it 'should work' do
      expect(instance.dn_ai_causal).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "dn_ai_destination"' do
    it 'should work' do
      expect(instance.dn_ai_destination).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "dn_ai_transporter"' do
    it 'should work' do
      expect(instance.dn_ai_transporter).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "dn_ai_notes"' do
    it 'should work' do
      expect(instance.dn_ai_notes).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "is_marked"' do
    it 'should work' do
      expect(instance.is_marked).to be(true).or be(false)
    end
  end

  describe 'test attribute "amount_net"' do
    it 'should work' do
      expect(instance.amount_net).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_vat"' do
    it 'should work' do
      expect(instance.amount_vat).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_gross"' do
    it 'should work' do
      expect(instance.amount_gross).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_rivalsa"' do
    it 'should work' do
      expect(instance.amount_rivalsa).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_cassa"' do
    it 'should work' do
      expect(instance.amount_cassa).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_withholding_tax"' do
    it 'should work' do
      expect(instance.amount_withholding_tax).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_other_withholding_tax"' do
    it 'should work' do
      expect(instance.amount_other_withholding_tax).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "extra_data"' do
    it 'should work' do
      expect(instance.extra_data).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "seen_date"' do
    it 'should work' do
      expect(instance.seen_date).to be_a_kind_of(Date)
    end
  end

  describe 'test attribute "next_due_date"' do
    it 'should work' do
      expect(instance.next_due_date).to be_a_kind_of(Date)
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      expect(instance.url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "attachment_url"' do
    it 'should work' do
      expect(instance.attachment_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "attachment_token"' do
    it 'should work' do
      expect(instance.attachment_token).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "ei_raw"' do
    it 'should work' do
      expect(instance.ei_raw).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "show_tspay_button"' do
    it 'should work' do
      expect(instance.show_tspay_button).to be(true).or be(false)
    end
  end

  describe 'test attribute "year"' do
    it 'should work' do
      expect(instance.year).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "amount_rivalsa_taxable"' do
    it 'should work' do
      expect(instance.amount_rivalsa_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_global_cassa_taxable"' do
    it 'should work' do
      expect(instance.amount_global_cassa_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_cassa_taxable"' do
    it 'should work' do
      expect(instance.amount_cassa_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_cassa2"' do
    it 'should work' do
      expect(instance.amount_cassa2).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_cassa2_taxable"' do
    it 'should work' do
      expect(instance.amount_cassa2_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_withholding_tax_taxable"' do
    it 'should work' do
      expect(instance.amount_withholding_tax_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_enasarco_taxable"' do
    it 'should work' do
      expect(instance.amount_enasarco_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_other_withholding_tax_taxable"' do
    it 'should work' do
      expect(instance.amount_other_withholding_tax_taxable).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "ei_cassa_type"' do
    it 'should work' do
      expect(instance.ei_cassa_type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "ei_cassa2_type"' do
    it 'should work' do
      expect(instance.ei_cassa2_type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "ei_withholding_tax_causal"' do
    it 'should work' do
      expect(instance.ei_withholding_tax_causal).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "ei_other_withholding_tax_type"' do
    it 'should work' do
      expect(instance.ei_other_withholding_tax_type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "ei_other_withholding_tax_causal"' do
    it 'should work' do
      expect(instance.ei_other_withholding_tax_causal).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "amount_due_discount"' do
    it 'should work' do
      expect(instance.amount_due_discount).to be_a_kind_of(Float)
    end
  end

end
