=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::ListClientsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::ListClientsResponse do
  instance = FattureInCloud_Ruby_Sdk::ListClientsResponse.new
  instance.current_page = 2;
  instance.first_page_url = "page=1";
  instance.from = 1;
  instance.last_page = 3;
  instance.last_page_url = "page=3";
  instance.next_page_url = "page=3";
  instance.path = "/archive";
  instance.per_page = 50;
  instance.prev_page_url = "page=1";
  instance.to = 3;
  instance.total = 155;
  instance.data = [
    {
      id: 16451,
      code: "AE86",
      name: "Avv. Maria Rossi",
      type: "person",
      first_name: "Maria",
      last_name: "Rossi",
      contact_person: "",
      vat_number: "IT12345640962",
      tax_code: "BLTGNI5ABCDA794E",
      address_street: "Via Roma, 1",
      address_postal_code: "20900",
      address_city: "Milano",
      address_province: "MI",
      address_extra: "",
      country: "Italia",
      email: "maria.rossi@example.com",
      certified_email: "maria.rossi@pec.example.com",
      phone: "1234567890",
      fax: "",
      notes: "",
      created_at: "2021-04-29",
      updated_at: "2021-04-29",
      default_payment_terms: 1,
      default_payment_terms_type: "standard",
      bank_name: "Indesa",
      bank_iban: "IT40P123456781000000123456",
      bank_swift_code: "AK86PCT",
      shipping_address: "Corso Magellano 4",
      e_invoice: true,
      ei_code: "111111",
      default_vat: {
        id: 54321,
        value: 45,
        description: "",
        is_disabled: false
      },
      default_payment_method: {
        id: 386092,
        name: "Credit card"
      }
    },
    {
      id: 25330696,
      code: "PD00",
      name: "Mario Rossi",
      type: "person",
      first_name: "Mario",
      last_name: "Rossi",
      contact_person: "",
      vat_number: "IT1234567890",
      tax_code: "ABCDEF12G34H567I",
      address_street: "Via largo augusto 123",
      address_postal_code: "21012",
      address_city: "Bergamo",
      address_province: "BG",
      address_extra: "",
      country: "Italia",
      email: "info@mariorossi.it",
      certified_email: "info@pec.mariorossi.it",
      phone: "012345678",
      fax: "012345678",
      notes: "",
      created_at: "2021-04-29",
      default_payment_terms: 0,
      default_payment_terms_type: "standard",
      bank_name: "Monte dei Pascoli",
      bank_iban: "IT00P123456781000000123456",
      bank_swift_code: "APL86PCT",
      shipping_address: "Via Miilano 4",
      e_invoice: false,
      ei_code: "7654321",
      default_vat: {
        id: 66,
        value: 22,
        description: "",
        is_disabled: false
      },
      default_payment_method: nil
    }
  ]    
  
  describe 'test an instance of ListClientsResponse' do
    it 'should create an instance of ListClientsResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::ListClientsResponse)
    end
  end
  
  describe 'test attribute "current_page"' do
    it 'should work' do
      expect(instance.current_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "first_page_url"' do
    it 'should work' do
      expect(instance.first_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      expect(instance.from).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page"' do
    it 'should work' do
      expect(instance.last_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page_url"' do
    it 'should work' do
      expect(instance.last_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "next_page_url"' do
    it 'should work' do
      expect(instance.next_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      expect(instance.path).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
      expect(instance.per_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "prev_page_url"' do
    it 'should work' do
      expect(instance.prev_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      expect(instance.to).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      expect(instance.total).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
