=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::ListReceiptsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::ListReceiptsResponse do
  instance = FattureInCloud_Ruby_Sdk::ListReceiptsResponse.new
  instance.current_page = 2
  instance.first_page_url = "page=1"
  instance.from = 1
  instance.last_page = 3
  instance.last_page_url = "page=3"
  instance.next_page_url = "page=3"
  instance.path = "/archive"
  instance.per_page = 50
  instance.prev_page_url = "page=1"
  instance.to = 3
  instance.total = 155
  instance.data = [
    {
      id: 12345,
      date: "2021-08-20",
      number: 5,
      numeration: "REC005",
      amount_net: 16.39,
      amount_vat: 3.61,
      amount_gross: 20,
      use_gross_prices: true,
      type: "sales_receipt",
      description: "cassa 1",
      rc_center: "",
      created_at: "2021-08-20",
      updated_at: "2021-08-20",
      payment_account: {
        id: 222,
        name: "carta di credito"
      },
      items_list: [
        {
          id: 666,
          amount_net: 10,
          amount_vat: 2.2,
          amount_gross: 12.2,
          category: "altro",
          vat: {
            id: 0,
            value: 22,
            description: "iva"
          }
        },
        {
          id: 777,
          amount_net: 100,
          amount_vat: 4,
          amount_gross: 104,
          category: "altro",
          vat: {
            id: 0,
            value: 22,
            description: "iva"
          }
        }
      ]
    },
    {
      id: 12346,
      date: "2021-08-19",
      number: 6,
      numeration: "REC006",
      amount_net: 8.2,
      amount_vat: 1.8,
      amount_gross: 10,
      use_gross_prices: true,
      type: "sales_receipt",
      description: "cassa 1",
      rc_center: "",
      created_at: "2021-08-19",
      updated_at: "2021-08-19",
      payment_account: {
        id: 555,
        name: "contanti"
      },
      items_list: [
        {
          id: 888,
          amount_net: 8.2,
          amount_vat: 1.8,
          amount_gross: 10,
          category: "altro",
          vat: {
            id: 0,
            value: 22,
            description: "iva"
          }
        }
      ]
    }
  ]    
  describe 'test an instance of ListReceiptsResponse' do
    it 'should create an instance of ListReceiptsResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::ListReceiptsResponse)
    end
  end

  describe 'test attribute "current_page"' do
  it 'should work' do
    expect(instance.current_page).to be_a_kind_of(Numeric)
  end
end

  describe 'test attribute "first_page_url"' do
    it 'should work' do
      expect(instance.first_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      expect(instance.from).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page"' do
    it 'should work' do
      expect(instance.last_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page_url"' do
    it 'should work' do
      expect(instance.last_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "next_page_url"' do
    it 'should work' do
      expect(instance.next_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      expect(instance.path).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
      expect(instance.per_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "prev_page_url"' do
    it 'should work' do
      expect(instance.prev_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      expect(instance.to).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      expect(instance.total).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
