=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::ListReceivedDocumentsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::ListReceivedDocumentsResponse do
  instance = FattureInCloud_Ruby_Sdk::ListReceivedDocumentsResponse.new
  instance.current_page = 2;
  instance.first_page_url = "page=1";
  instance.from = 1;
  instance.last_page = 3;
  instance.last_page_url = "page=3";
  instance.next_page_url = "page=3";
  instance.path = "/archive";
  instance.per_page = 50;
  instance.prev_page_url = "page=1";
  instance.to = 3;
  instance.total = 155;
  instance.data = [
    {
      id: 12345,
      type: "expense",
      description: "Soggiorno di lavoro",
      amortization: 1,
      rc_center: "",
      invoice_number: "",
      is_marked: false,
      is_detailed: false,
      e_invoice: false,
      created_at: "2021-08-15",
      updated_at: "2021-08-15",
      entity: {
        id: 111,
        name: "Hotel Rubino Palace"
      },
      date: "2021-08-15",
      next_due_date: "2021-08-15",
      currency: {
        id: "EUR",
        exchange_rate: "1.00000",
        symbol: "€"
      },
      amount_net: 592,
      amount_vat: 0,
      amount_gross: 592,
      amount_withholding_tax: 0,
      amount_other_withholding_tax: 0,
      tax_deductibility: 50,
      vat_deductibility: 100,
      items_list:nil,
      payments_list: [
        {
          amount: 592,
          due_date: "2021-08-15",
          paid_date: "2021-08-15",
          id: 777,
          payment_terms: {
            days: 0,
            type: "standard"
          },
          status: "paid",
          payment_account: {
            id: 222,
            name: "Contanti",
            virtual: false
          }
        }
      ],
      attachment_url: "spesa_ger5i783t45hu6ti.pdf",
      attachment_preview_url:nil,
      extra_data:nil
    },
    {
      id: 12346,
      type: "expense",
      description: "Assicurazione RCA",
      iamortization: 1,
      rc_center: "",
      invoice_number: "",
      is_marked: false,
      is_detailed: false,
      e_invoice: false,
      created_at: "2021-08-09",
      updated_at: "2021-08-09",
      entity: {
        id: 89,
        name: "Indesa Assicurazioni S.P.A."
      },
      date: "2021-08-08",
      next_due_date: "2021-08-08",
      currency: {
        id: "EUR",
        exchange_rate: "1.00000",
        symbol: "€"
      },
      amount_net: 645.69,
      amount_vat: 0,
      amount_gross: 645.69,
      amount_withholding_tax: 0,
      amount_other_withholding_tax: 0,
      tax_deductibility: 50,
      vat_deductibility: 100,
      items_list:nil,
      payments_list: [
        {
          amount: 645.69,
          due_date: "2021-08-08",
          paid_date: "2021-08-08",
          id: 999,
          payment_terms: {
            days: 0,
            type: "standard"
          },
          status: "paid",
          payment_account: {
            id: 333,
            name: "Carta conto",
            virtual: false
          }
        }
      ],
      attachment_url: "spesa_gjsd567e5hu6ti.pdf",
      attachment_preview_url:nil,
      extra_data:nil
    }
  ]

  describe 'test an instance of ListReceivedDocumentsResponse' do
    it 'should create an instance of ListReceivedDocumentsResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::ListReceivedDocumentsResponse)
    end
  end

    describe 'test attribute "current_page"' do
    it 'should work' do
      expect(instance.current_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "first_page_url"' do
    it 'should work' do
      expect(instance.first_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "from"' do
    it 'should work' do
      expect(instance.from).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page"' do
    it 'should work' do
      expect(instance.last_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "last_page_url"' do
    it 'should work' do
      expect(instance.last_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "next_page_url"' do
    it 'should work' do
      expect(instance.next_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      expect(instance.path).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "per_page"' do
    it 'should work' do
      expect(instance.per_page).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "prev_page_url"' do
    it 'should work' do
      expect(instance.prev_page_url).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "to"' do
    it 'should work' do
      expect(instance.to).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "total"' do
    it 'should work' do
      expect(instance.total).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
