=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::ListVatTypesResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::ListVatTypesResponse do
  instance = FattureInCloud_Ruby_Sdk::ListVatTypesResponse.new
  instance.data = [
    {
      id: 0,
      value: 22,
      description: "Non imponibile art. 123",
      notes: "IVA non imponibile ai sensi dell\'articolo 123, comma 2",
      e_invoice: "string",
      ei_type: 2,
      ei_description: "string",
      editable: true
    },
    {
      id: 1010,
      value: 0,
      description: "NON IMPONIBILE IVA EX ART. 8 COMMA 1 LETT.A",
      notes: "",
      e_invoice: false,
      ei_type: 0,
      ei_description: nil,
      is_disabled: false,
      editable: true
    }
  ]

  describe 'test an instance of ListVatTypesResponse' do
    it 'should create an instance of ListVatTypesResponse' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::ListVatTypesResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      expect(instance.data).to be_a_kind_of(Object)
    end
  end

end
