=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.1.5
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::PriceList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::PriceList do
  instance = FattureInCloud_Ruby_Sdk::PriceList.new
  instance.id = '12345'
  instance.name = 'listino 1'
  instance.prices_type = 'net'
  instance.is_default = true
  instance.valid_from = '2021-01-01'
  instance.valid_to = '2021-12-31'
  instance.type = 'sell'

  describe 'test an instance of PriceList' do
    it 'should create an instance of PriceList' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::PriceList)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance.id).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      expect(instance.name).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "prices_type"' do
    it 'should work' do
      expect(instance.prices_type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "is_default"' do
    it 'should work' do
      expect(instance.is_default).to be_a_kind_of(TrueClass)
    end
  end

  describe 'test attribute "valid_from"' do
    it 'should work' do
      expect(instance.valid_from).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "valid_to"' do
    it 'should work' do
      expect(instance.valid_to).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      expect(instance.type).to be_a_kind_of(String)
    end
  end

end
