=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FattureInCloud_Ruby_Sdk::Receipt
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FattureInCloud_Ruby_Sdk::Receipt do
  instance = FattureInCloud_Ruby_Sdk::Receipt.new
  instance.id = 12345
  instance.date = Date.new(2021, 12, 21)
  instance.number = 5
  instance.numeration = "REC005"
  instance.amount_net = 16.39
  instance.amount_vat = 3.61
  instance.amount_gross = 20.0
  instance.use_gross_prices = true
  instance.type = "sales_receipt"
  instance.description = "cassa 1"
  instance.rc_center = ""
  instance.created_at = "2021-08-20"
  instance.updated_at = "2021-08-20"
  instance.payment_account = {
    id: 222,
    name: "carta di credito"
  },
  instance.items_list = [
      {
        id: 666,
        amount_net: 10,
        amount_vat: 2.2,
        amount_gross: 12.2,
        category: "altro",
        vat: {
          id: 0,
          value: 22,
          description: "iva"
        }
      }
  ]    

  describe 'test an instance of Receipt' do
    it 'should create an instance of Receipt' do
      expect(instance).to be_instance_of(FattureInCloud_Ruby_Sdk::Receipt)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      expect(instance.id).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      expect(instance.date).to be_a_kind_of(Date)
    end
  end

  describe 'test attribute "number"' do
    it 'should work' do
      expect(instance.number).to be_a_kind_of(Numeric)
    end
  end

  describe 'test attribute "numeration"' do
    it 'should work' do
      expect(instance.numeration).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "amount_net"' do
    it 'should work' do
      expect(instance.amount_net).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_vat"' do
    it 'should work' do
      expect(instance.amount_vat).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "amount_gross"' do
    it 'should work' do
      expect(instance.amount_gross).to be_a_kind_of(Float)
    end
  end

  describe 'test attribute "use_gross_prices"' do
    it 'should work' do
      expect(instance.use_gross_prices).to be(true).or be(false)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      expect(instance.type).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      expect(instance.description).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "rc_center"' do
    it 'should work' do
      expect(instance.rc_center).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "created_at"' do
    it 'should work' do
      expect(instance.created_at).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "updated_at"' do
    it 'should work' do
      expect(instance.updated_at).to be_a_kind_of(String)
    end
  end

  describe 'test attribute "payment_account"' do
    it 'should work' do
      expect(instance.payment_account).to be_a_kind_of(Object)
    end
  end

  describe 'test attribute "items_list"' do
    it 'should work' do
      expect(instance.items_list).to be_a_kind_of(Object)
    end
  end

end
