=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.0.7
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for module_name::SupplierType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe module_name::SupplierType do
  let(:instance) { module_name::SupplierType.new }

  describe 'test an instance of SupplierType' do
    it 'should create an instance of SupplierType' do
      expect(instance).to be_instance_of(module_name::SupplierType)
    end
  end
end
