=begin
#Fatture in Cloud API v2 - API Reference

#Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.

The version of the OpenAPI document: 2.1.8
Contact: info@fattureincloud.it
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module FattureInCloud_Ruby_Sdk
  class PendingReceivedDocument < ApiModelBase
    # Pending received document id
    attr_accessor :id

    # Pending received document date
    attr_accessor :date

    # Pending received document subject
    attr_accessor :subject

    # Pending received document filename
    attr_accessor :filename

    attr_accessor :type

    # [Temporary] [Read Only] Pending received document url of the attached file
    attr_accessor :attachment_url

    # [Read Only] Pending received document total gross amount
    attr_accessor :amount_gross

    attr_accessor :currency

    attr_accessor :document_type

    # Pending received document supplier name
    attr_accessor :supplier_name

    # Pending received document cost center
    attr_accessor :cost_center

    # Pending received document category
    attr_accessor :category

    # Pending received document other attachments
    attr_accessor :other_attachments

    # Pending received document emission date
    attr_accessor :emssion_date

    attr_accessor :payments_list

    # Pending received document total net amount
    attr_accessor :amount_net

    # Pending received document total vat amount
    attr_accessor :amount_vat

    # Pending received document import error
    attr_accessor :import_error

    attr_accessor :extracted_data

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'date' => :'date',
        :'subject' => :'subject',
        :'filename' => :'filename',
        :'type' => :'type',
        :'attachment_url' => :'attachment_url',
        :'amount_gross' => :'amount_gross',
        :'currency' => :'currency',
        :'document_type' => :'document_type',
        :'supplier_name' => :'supplier_name',
        :'cost_center' => :'cost_center',
        :'category' => :'category',
        :'other_attachments' => :'other_attachments',
        :'emssion_date' => :'emssion_date',
        :'payments_list' => :'payments_list',
        :'amount_net' => :'amount_net',
        :'amount_vat' => :'amount_vat',
        :'import_error' => :'import_error',
        :'extracted_data' => :'extracted_data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'date' => :'Date',
        :'subject' => :'String',
        :'filename' => :'String',
        :'type' => :'PendingReceivedDocumentType',
        :'attachment_url' => :'String',
        :'amount_gross' => :'Float',
        :'currency' => :'Currency',
        :'document_type' => :'ReceivedDocumentType',
        :'supplier_name' => :'String',
        :'cost_center' => :'String',
        :'category' => :'String',
        :'other_attachments' => :'Array<Attachment>',
        :'emssion_date' => :'Date',
        :'payments_list' => :'Array<PendingReceivedDocumentPaymentsListItem>',
        :'amount_net' => :'Float',
        :'amount_vat' => :'Float',
        :'import_error' => :'String',
        :'extracted_data' => :'PendingReceivedDocumentExtractedData'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'date',
        :'subject',
        :'filename',
        :'attachment_url',
        :'amount_gross',
        :'supplier_name',
        :'cost_center',
        :'category',
        :'other_attachments',
        :'emssion_date',
        :'payments_list',
        :'amount_net',
        :'amount_vat',
        :'import_error',
        :'extracted_data'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FattureInCloud_Ruby_Sdk::PendingReceivedDocument` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FattureInCloud_Ruby_Sdk::PendingReceivedDocument`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'subject')
        self.subject = attributes[:'subject']
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = 'agyo'
      end

      if attributes.key?(:'attachment_url')
        self.attachment_url = attributes[:'attachment_url']
      end

      if attributes.key?(:'amount_gross')
        self.amount_gross = attributes[:'amount_gross']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'document_type')
        self.document_type = attributes[:'document_type']
      else
        self.document_type = 'expense'
      end

      if attributes.key?(:'supplier_name')
        self.supplier_name = attributes[:'supplier_name']
      end

      if attributes.key?(:'cost_center')
        self.cost_center = attributes[:'cost_center']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'other_attachments')
        if (value = attributes[:'other_attachments']).is_a?(Array)
          self.other_attachments = value
        end
      end

      if attributes.key?(:'emssion_date')
        self.emssion_date = attributes[:'emssion_date']
      end

      if attributes.key?(:'payments_list')
        if (value = attributes[:'payments_list']).is_a?(Array)
          self.payments_list = value
        end
      end

      if attributes.key?(:'amount_net')
        self.amount_net = attributes[:'amount_net']
      end

      if attributes.key?(:'amount_vat')
        self.amount_vat = attributes[:'amount_vat']
      end

      if attributes.key?(:'import_error')
        self.import_error = attributes[:'import_error']
      end

      if attributes.key?(:'extracted_data')
        self.extracted_data = attributes[:'extracted_data']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          date == o.date &&
          subject == o.subject &&
          filename == o.filename &&
          type == o.type &&
          attachment_url == o.attachment_url &&
          amount_gross == o.amount_gross &&
          currency == o.currency &&
          document_type == o.document_type &&
          supplier_name == o.supplier_name &&
          cost_center == o.cost_center &&
          category == o.category &&
          other_attachments == o.other_attachments &&
          emssion_date == o.emssion_date &&
          payments_list == o.payments_list &&
          amount_net == o.amount_net &&
          amount_vat == o.amount_vat &&
          import_error == o.import_error &&
          extracted_data == o.extracted_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, date, subject, filename, type, attachment_url, amount_gross, currency, document_type, supplier_name, cost_center, category, other_attachments, emssion_date, payments_list, amount_net, amount_vat, import_error, extracted_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      when :Hash
        value
      else # model
        # models (e.g. Pet) or oneOf
        klass = FattureInCloud_Ruby_Sdk.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
